version: "3"
services: 
  frontend: 
    restart: always
    build: ./frontend
    environment: 
      - "BACKEND_APP_ENDPOINT=backend"
    ports: 
      - "3000:3000"
    networks:
      - frontnet

  backend:
    restart: always
    build: ./backend
    ports: 
      - "80:80"
      - "8080:8080"
    environment: 
      - "CONNECTION=mongo"
    depends_on:
      - mongo
    networks:
      - mongonet
      - frontnet

  mongo:
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mongonet
    environment:
      MONGO_INITDB_DATABASE: talkingCampus
    volumes:
      - ./mongo_scripts:/docker-entrypoint-initdb.d
  
networks:
  frontnet:
  mongonet:
