version: "3"
services: 
  frontend: 
    restart: always
    build: ./frontend
    networks:
      - frontnet

  backend:
    restart: always
    build: ./backend
    depends_on:
      - mongo
    networks:
      - mongonet
      - frontnet

  mongo:
    restart: always
    image: mongo
    networks:
      - mongonet
    volumes:
      - ./mongo_scripts/:/docker-entrypoint-initdb.d/
  
networks:
  frontnet:
  mongonet: