version: "3"
services: 
  frontend: 
    restart: always
    build: ./frontend
    environment: 
      - "REACT_APP_ENDPOINT=backend"
    ports: 
      - "3000:3000"
    networks:
      - frontnet

  backend:
    restart: always
    build: ./backend
    ports: 
      - "80:80"
      - "8080:8080"
    environment: 
      - "CONNECTION=mongo"
    depends_on:
      - mongo
    networks:
      - mongonet
      - frontnet

  mongo:
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mongonet
    volumes:
      - ./mongo_scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      - "MONGO_INITDB_DATABASE=talkingCampus"
  
networks:
  frontnet:
  mongonet: