version: "3"
services: 
  frontend: 
    build: ./frontend
    networks:
      - frontnet

  backend:
    build: ./backend
    depends_on:
      - mongo
    networks:
      - mongonet
      - frontnet

  mongo:
    image: mongo
    networks:
      - mongonet
    volumes:
      - ./mongo_scripts/:/docker-entrypoint-initdb.d/
  
  networks:
    frontnet:
    mongonet: