version: "3"
services: 
  frontend: 
    build: ./frontend
    networks:
      - front_net

  backend:
    build: ./backend
    depends_on:
      - mongo
    networks:
      - mongo-net
      - front-net

  mongo:
    image: mongo
    networks:
      - mongo-net
    volumes:
      - ./mongo_scripts/:/docker-entrypoint-initdb.d/
  
  networks:
    front-net:
    mongo-net: